### ISSUE TITLE
Supabase setup

### ISSUE THREAD

**Issue by tommerty** [GeneralTyres/NextJS-Supabase-Auth-Template#2]
Like another user said in #1, I'd like to know how your Supabase database is set up. I'm very new to all this and usually just build a frontend but I'm trying to learn how to create databases and stumbled upon this repository.

I've changed google for discord inside `providers` and it pulls the data however I do get a 

> Error loading user data!

error message on `account`, and it's not storing anything in supabase because frankly I've not set it up. Could you include a basic guide on creating the actual supabase database?

Thanks very much in advance!

**Comment by GeneralTyres** [comment]
Hi Tommerty!

I didn't expect someone to use this template other than me so I apologise for the lack in documentation. I am also still a novice when it comes to Supabase and also NextJS(React) and this project was kind of like experiment for me. Having said that, I will share what I know.

This entire project is based on the tutorial that can be found in the Supabase docs.
https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs#supabase-auth-helpers

To set up your database, you can run the provide "User Management" Query as stated in the tutorial. I think I removed the website field though. There is also a link to their own repository for the example.

When it comes to your user errors, I am not sure what to recommend. However, I will say that if you are using Google then you need to set up a Google account on Firebase or Google API for the credentials.

Hope this helps!
